=== NazarUsik/epamCourse/Practice7/kar/input2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  XML schema -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://nure.ua/ohol/p7"
            xmlns:tns="http://nure.ua/ohol/p7">
    <xsd:element name="Sites">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Site" type="tns:typeSite" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="typeSite">
        <xsd:sequence>
            <xsd:element name="Title" type="xsd:string"/>
            <xsd:element name="Type" type="typePages"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="typePages">
        <xsd:sequence>
            <xsd:element name="Advert" type="tns:typeAdvert"/>
            <xsd:element name="News" type="tns:typeNews"/>
            <xsd:element name="Portal" type="tns:typePortal"/>
            <xsd:element name="Mirror" type="tns:typeMirror"/>
        </xsd:sequence>
    </xsd:complexType>

    <!--    <xsd:complexType name="typeChars">-->
    <!--        <xsd:sequence>-->
    <!--            <xsd:element name ="Email" type ="xsd:boolean"/>-->
    <!--            <xsd:element name ="AllovedNews" type ="xsd:boolean"/>-->
    <!--            <xsd:element name ="AllowedArchive" type ="xsd:boolean"/>-->
    <!--            <xsd:element name ="AllowedVote" type ="tns:typeVote"/>-->
    <!--            <xsd:element name ="isFreeToDownload" type ="xsd:boolean"/>-->
    <!--        </xsd:sequence>-->
    <!--    </xsd:complexType>-->

    <xsd:complexType name="typeVote">
        <xsd:sequence>
            <xsd:element name="true" type="tns:typeAuthorize"/>
            <xsd:element name="false"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="typeAuthorize">
        <xsd:sequence>
            <xsd:element name="anonymous" type="xsd:string"/>
            <xsd:element name="authorized" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="typeAdvert">
<!--        <xsd:complexContent>-->
            <!--            <xsd:restriction base="tns:typeChars">-->
            <xsd:sequence>
                <xsd:element name="Email" type="xsd:boolean" fixed="false"/>
                <xsd:element name="AllovedNews" type="xsd:boolean" fixed="false"/>
                <xsd:element name="AllowedArchive" type="xsd:boolean" fixed="false"/>
                <xsd:element name="AllowedVote" type="tns:typeVote"/>
                <xsd:element name="isFreeToDownload" type="xsd:boolean"/>
            </xsd:sequence>
            <!--            </xsd:restriction>-->
<!--        </xsd:complexContent>-->
    </xsd:complexType>


    <xsd:complexType name="typeNews">
<!--        <xsd:complexContent>-->
            <!--            <xsd:restriction base="tns:typeChars">-->
            <xsd:sequence>
                <xsd:element name="Email" type="xsd:boolean" fixed="true"/>
                <xsd:element name="AllovedNews" type="xsd:boolean" fixed="true"/>
                <xsd:element name="AllowedArchive" type="xsd:boolean" fixed="false"/>
                <xsd:element name="AllowedVote" type="tns:typeVote"/>
                <xsd:element name="isFreeToDownload" type="xsd:boolean"/>
            </xsd:sequence>
            <!--            </xsd:restriction>-->
<!--        </xsd:complexContent>-->
    </xsd:complexType>

    <xsd:complexType name="typePortal">
<!--        <xsd:complexContent>-->
            <!--            <xsd:restriction base="tns:typeChars">-->
            <xsd:sequence>
                <xsd:element name="Email" type="xsd:boolean" fixed="true"/>
                <xsd:element name="AllovedNews" type="xsd:boolean" fixed="false"/>
                <xsd:element name="AllowedArchive" type="xsd:boolean" fixed="false"/>
                <xsd:element name="AllowedVote" type="tns:typeVote"/>
                <xsd:element name="isFreeToDownload" type="xsd:boolean"/>
            </xsd:sequence>
            <!--            </xsd:restriction>-->
<!--        </xsd:complexContent>-->
    </xsd:complexType>

    <xsd:complexType name="typeMirror">
<!--        <xsd:complexContent>-->
            <!--            <xsd:restriction base="tns:typeChars">-->
            <xsd:sequence>
                <xsd:element name="Email" type="xsd:boolean" fixed="true"/>
                <xsd:element name="AllovedNews" type="xsd:boolean" fixed="false"/>
                <xsd:element name="AllowedArchive" type="xsd:boolean" fixed="true"/>
                <xsd:element name="AllowedVote" type="tns:typeVote"/>
                <xsd:element name="isFreeToDownload" type="xsd:boolean"/>
            </xsd:sequence>
            <!--            </xsd:restriction>-->
<!--        </xsd:complexContent>-->
    </xsd:complexType>

</xsd:schema>

=== NazarUsik/epamCourse/Practice7/kar/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Input XML document. This XML is valid against Test.xsd XML schema-->

<p7:Sites xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:p7="http://nure.ua/ohol/p7"
         xsi:schemaLocation="http://nure.ua/ohol/p7  input2.xsd" >
    <Site>
        <Title>Site</Title>
        <Type>
            <Advert>
                <p7:Email></Email>
                <p7:AllovedNews></AllovedNews>
                <p7:AllowedArchive></AllowedArchive>
                <p7:AllowedVote>
                    <p7:true>
                        <p7:anonymous></anonymous>
                        <p7:authorized></authorized>
                    </true>
                    <p7:false></false>
                </AllowedVote>
                <p7:isFreeToDownload></isFreeToDownload>
            </Advert>
        </Type>
       
    </Site>
</p7:Sites>
